data:
  train_shape: [64, 64, 64]
  in_channels: 1
  images:
    shared: "data/default/2d"
    axis0: null
    axis1: null
    axis2: null

anchor:
  empty_prob: 0.1
  min_gap: 1

dl:
  batch_size: 8
  num_workers: 0
  pin_memory: true

generator:
  enc_channels: [64, 128, 256, 512]
  dec_channels: [512, 256, 128, 64]
  noise_channels: 32
  output: "tanh"

critic:
  channels: [1, 64, 128, 256, 512, 1]
  kernels: [4, 4, 4, 4, 4]
  strides: [2, 2, 2, 2, 2]
  paddings: [1, 1, 1, 1, 0]

optimizer:
  lr: 0.0001
  betas: [0.9, 0.99]

trainer:
  gp_lambda: 10.0
  recon_lambda: 1.0
  gen_freq: 5
  steps: 360000
  save_freq: 1000

device: "cuda"
